[package]
name = "hunt-2"
version = "0.1.0"
authors = ["Michael <bausanomichal@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.1"
rand = "0.7"
parking_lot = "0.11"
crossbeam-channel = "0.4"
shrinkwraprs = "0.3"
